name: Training theme
type: theme
base theme: olivero
core_version_requirement: ^8 || ^9
description: 'A training theme, inherit from Olivero.'
libraries:
  - 'training_theme/main'

regions:
  header: 'Header'
  primary_menu: 'Primary menu'
  secondary_menu: 'Secondary menu'
  highlighted: 'Highlighted'
  breadcrumb: 'Breadcrumb'
  social: 'Social Bar'
  content_above: 'Content Above'
  content: 'Content'
  sidebar: 'Sidebar'
  footer_top: 'Footer Top'
  footer_bottom: 'Footer Bottom'